ALTER TABLE records ADD COLUMN sacks REAL NOT NULL DEFAULT 0;
ALTER TABLE records ADD COLUMN unit_price INTEGER NOT NULL DEFAULT 0;
ALTER TABLE records ADD COLUMN receipt_name TEXT NOT NULL DEFAULT '';
ALTER TABLE records ADD COLUMN receipt_data TEXT NOT NULL DEFAULT '';
