import {build} from 'esbuild';
import {readFile,mkdir,writeFile,cp,rm} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),out=path.join(root,'android/native/assets');
await rm(out,{recursive:true,force:true});await mkdir(out,{recursive:true});
const receipt=path.join(root,'android/web/receipt.tsx'),native=path.join(root,'android/web/native.ts');
const adapt={name:'android-app-adapter',setup(builder){
 builder.onLoad({filter:/\/app\/page\.tsx$/},async args=>{let source=await readFile(args.path,'utf8');source=`import Receipt from ${JSON.stringify(receipt)};\nimport {saveDrive} from ${JSON.stringify(native)};\n`+source;
  const start=source.indexOf('function exportCsv()'),end=source.indexOf('\nconst visible=',start);if(start<0||end<0)throw Error('CSV adapter anchor changed');
  const old=source.slice(start,end),csv=old.slice(old.indexOf("const cols="),old.indexOf('const url='));
  source=source.slice(0,start)+`async function exportCsv(){try{${csv}await saveDrive(csv,'text/csv','catatan-pupuk-'+new Date().toISOString().replace(/[:.]/g,'-')+'.csv');setNotice('CSV ditulis ke file Drive. Periksa status unggahan di aplikasi Drive.');}catch(e){setError((e as Error).message);}}`+source.slice(end);
  const anchor='<label>Catatan (opsional)';if(!source.includes(anchor))throw Error('Receipt adapter anchor changed');
  source=source.replace(anchor,'<Receipt name={form.receiptName} data={form.receiptData} onChange={value=>setForm(current=>({...current,...value}))}/>'+anchor);
  return {contents:source,loader:'tsx',resolveDir:path.dirname(args.path)};
 });
 builder.onLoad({filter:/\/app\/reports\.tsx$/},async args=>{let source=await readFile(args.path,'utf8');source=`import {saveDrive} from ${JSON.stringify(native)};\n`+source;
  source=source.replace(/ function download[^\n]+/,' async function download(bytes:Uint8Array|string,mime:string,filename:string){await saveDrive(bytes,mime,filename);}');
  source=source.replace('download(JSON.stringify','await download(JSON.stringify').replace('download(bytes,fileType','await download(bytes,fileType');
  source=source.replace('file.size>5_000_000','file.size>64_000_000').replace('Cadangan maksimal 5 MB.','Cadangan maksimal 64 MB.');
  source=source.replace(/setMessage\(`Cadangan lengkap[^;]+;/,'setMessage(`Cadangan lengkap ${result.recordCount} transaksi ditulis ke file Drive. Periksa status unggahan di aplikasi Drive.`);');
  source=source.replace(/setMessage\(`\$\{manual\?[^;]+;/,'setMessage(`File ${fileType===\'pdf\'?\'PDF\':\'Excel\'} ditulis ke file Drive. Periksa status unggahan di aplikasi Drive.`);');
  const start=source.indexOf('<div className="drive-state">'),end=source.indexOf('<div className="backup-box">',start);if(start<0||end<0)throw Error('Drive report adapter anchor changed');
  source=source.slice(0,start)+'<div className="drive-state"><Cloud size={30}/><div><strong>File data di Google Drive</strong><p>Perubahan transaksi disimpan ke HP terlebih dahulu, lalu dicoba ditulis ke file Drive. Jika belum terkirim, status di bagian atas tetap menunjukkan data tertunda.</p><p>Saat membuat laporan atau cadangan, pilih Google Drive sebagai tempat menyimpan. Drive menyelesaikan unggahan melalui aplikasi Drive di HP.</p></div></div>'+source.slice(end);
  source=source.replace('Unduh seluruh transaksi terbaru dalam tiga format. Simpan ketiganya di tempat yang aman sebagai salinan tambahan.','Simpan seluruh data terbaru sebagai salinan tambahan di Google Drive. Nama file memuat tanggal dan jam.');
  source=source.replace('Unduh laporan PDF','Simpan PDF ke Drive').replace('Unduh Excel (.xlsx)','Simpan Excel ke Drive');
  return{contents:source,loader:'tsx',resolveDir:path.dirname(args.path)};
 });
}};
await build({entryPoints:[path.join(root,'android/web/main.tsx')],bundle:true,minify:true,sourcemap:false,outfile:path.join(out,'app.js'),platform:'browser',target:'es2020',jsx:'automatic',tsconfig:path.join(root,'tsconfig.json'),plugins:[adapt],define:{'process.env.NODE_ENV':'"production"'},logLevel:'warning'});
const css=(await readFile(path.join(root,'app/globals.css'),'utf8')).replace(/^@import[^\n]+\n/,'')+'\n'+await readFile(path.join(root,'android/web/android.css'),'utf8');
await writeFile(path.join(out,'app.css'),css);await cp(path.join(root,'public/fonts'),path.join(out,'fonts'),{recursive:true});
await writeFile(path.join(out,'index.html'),'<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="light"><title>Buku Pupuk</title><link rel="stylesheet" href="/app.css"></head><body><div id="root"></div><script src="/app.js"></script></body></html>');
console.log('Bundled Android UI, reports, fonts, receipt input, and Drive export adapter.');
