import {build} from 'esbuild';
import {readFile,mkdir,writeFile,cp,rm} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),out=path.join(root,'android/native/assets');
await rm(out,{recursive:true,force:true});await mkdir(out,{recursive:true});
await cp(path.join(root,'android/firebase/google-services.json'),path.join(out,'google-services.json'));
const receipt=path.join(root,'android/web/receipt.tsx'),native=path.join(root,'android/web/native.ts');
const copyright=path.join(root,'android/web/copyright.tsx');
const finance=path.join(root,'android/web/finance.tsx');
const navigation=path.join(root,'android/web/navigation.tsx');
function replaceOnce(source,anchor,replacement){if(!source.includes(anchor))throw Error('Mobile adapter anchor changed: '+anchor.slice(0,80));return source.replace(anchor,replacement);}
const adapt={name:'android-app-adapter',setup(builder){
 builder.onLoad({filter:/\/app\/page\.tsx$/},async args=>{let source=await readFile(args.path,'utf8');source=`import Receipt from ${JSON.stringify(receipt)};\nimport {saveDrive,currentStatus} from ${JSON.stringify(native)};\nimport {MobileHeader,BottomNavigation} from ${JSON.stringify(navigation)};\nimport Finance from ${JSON.stringify(finance)};\nimport AppCopyright from ${JSON.stringify(copyright)};\n`+source;
  const start=source.indexOf('function exportCsv()'),end=source.indexOf('\nconst visible=',start);if(start<0||end<0)throw Error('CSV adapter anchor changed');
  const old=source.slice(start,end),csv=old.slice(old.indexOf("const cols="),old.indexOf('const url='));
  source=source.slice(0,start)+`async function exportCsv(){try{${csv}await saveDrive(csv,'text/csv','catatan-pupuk-'+new Date().toISOString().replace(/[:.]/g,'-')+'.csv');setNotice('CSV ditulis ke file Drive. Periksa status unggahan di aplikasi Drive.');}catch(e){setError((e as Error).message);}}`+source.slice(end);
  const anchor='<label>Catatan (opsional)';if(!source.includes(anchor))throw Error('Receipt adapter anchor changed');
  source=source.replace(anchor,'<Receipt name={form.receiptName} data={form.receiptData} onChange={value=>setForm(current=>({...current,...value}))}/>'+anchor);
  const asideStart=source.indexOf('<aside>'),asideEnd=source.indexOf('</aside>',asideStart);if(asideStart<0||asideEnd<0)throw Error('Mobile navigation anchor changed');
  source=source.slice(0,asideStart)+source.slice(asideEnd+8);
  const headerStart=source.indexOf('<header>'),headerEnd=source.indexOf('</header>',headerStart);if(headerStart<0||headerEnd<0)throw Error('Mobile header anchor changed');
  source=source.slice(0,headerStart)+'<MobileHeader tab={tab}/>'+source.slice(headerEnd+9);
  source=replaceOnce(source,"{tab!=='Simulasi'&&<div className=\"cards\">","{tab==='Ringkasan'&&<div className=\"cards\">");
  source=replaceOnce(source,"{tab!=='Simulasi'&&<button className=\"primary\"", "{['Ringkasan','Pembelian','Penjualan','Anggota'].includes(tab)&&<button className=\"primary\"");
  source=replaceOnce(source,"tab==='Laporan & cadangan'?<Reports rows={rows}","['Laporan','Cadangan'].includes(tab)?<><Reports section={tab==='Cadangan'?'backup':'reports'} rows={rows}");
  source=replaceOnce(source,"window.dispatchEvent(new Event('buku-pupuk-restored'));}}/>:","window.dispatchEvent(new Event('buku-pupuk-restored'));}}/>{tab==='Laporan'&&<button className=\"mobile-csv\" onClick={exportCsv} disabled={!rows.length}><Download size={18}/>Simpan CSV ke Drive</button>}</>:");
  source=replaceOnce(source,"[tab,setTab]=useState('Ringkasan')","[tab,setTab]=useState(window.BukuMenu||'Ringkasan')");
  source=replaceOnce(source,'</main>{modal&&','</main><BottomNavigation tab={tab} onSelect={value=>{window.BukuMenu=value;setTab(value);}}/>{modal&&');
  source=source.replace("setNotice(editing?'Transaksi berhasil diperbarui. Stok, kas dan laporan dihitung ulang.':'Catatan berhasil disimpan.');","setNotice(editing?'Transaksi diperbarui.':'Catatan disimpan.');");
  source=replaceOnce(source,'<div className="table-wrap"><table>','<div className="table-wrap mobile-transactions"><table>');
  source=replaceOnce(source,'<td>{r.qty?', '<td data-label="Jumlah">{r.qty?');
  source=replaceOnce(source,'<td className="money">','<td className="money" data-label="Nilai transaksi">');
  source=replaceOnce(source,"{tab==='Simulasi'?null:tab==='Anggota'?","{tab==='Keuangan'?<Finance rows={rows} loading={loading} recordsError={error}/>:tab==='Simulasi'?null:tab==='Anggota'?");
  source=replaceOnce(source,'<footer>','<footer><AppCopyright/>');
  const actionIcons={'Pupuk masuk':'Package','Biaya angkut / bongkar':'Truck','Bayar distributor':'Wallet','Terima pelunasan':'ArrowDownToLine','Penarikan bank':'ArrowDownToLine'};
  for(const [text,icon] of Object.entries(actionIcons))source=source.replaceAll('>'+text+'</button>','><'+icon+' size={18}/>'+text+'</button>');
  return {contents:source,loader:'tsx',resolveDir:path.dirname(args.path)};
 });
 builder.onLoad({filter:/\/app\/reports\.tsx$/},async args=>{let source=await readFile(args.path,'utf8');source=`import {saveDrive} from ${JSON.stringify(native)};\n`+source;
  source=source.replace(/ function download[^\n]+/,' async function download(bytes:Uint8Array|string,mime:string,filename:string){await saveDrive(bytes,mime,filename);}');
  source=source.replace('download(JSON.stringify','await download(JSON.stringify').replace('download(bytes,fileType','await download(bytes,fileType');
  source=source.replace('file.size>5_000_000','file.size>64_000_000').replace('Cadangan maksimal 5 MB.','Cadangan maksimal 64 MB.');
  source=source.replace(/setMessage\(`Cadangan lengkap[^;]+;/,'setMessage(`Cadangan lengkap ${result.recordCount} transaksi ditulis ke file Drive. Periksa status unggahan di aplikasi Drive.`);');
  source=source.replace(/setMessage\(`\$\{manual\?[^;]+;/,'setMessage(`File ${fileType===\'pdf\'?\'PDF\':\'Excel\'} ditulis ke file Drive. Periksa status unggahan di aplikasi Drive.`);');
  source=source.replace('Unduh seluruh transaksi terbaru dalam tiga format. Simpan ketiganya di tempat yang aman sebagai salinan tambahan.','Simpan seluruh data terbaru sebagai salinan tambahan di Google Drive. Nama file memuat tanggal dan jam.');
  source=source.replace('Unduh laporan PDF','Simpan PDF ke Drive').replace('Unduh Excel (.xlsx)','Simpan Excel ke Drive');
  source=replaceOnce(source,'function Reports({rows}:{rows:RecordRow[];onRestored?:()=>Promise<void>})','function Reports({rows,section}:{rows:RecordRow[];onRestored?:()=>Promise<void>;section?:string})');
  source=replaceOnce(source,'<section className="panel"><div className="panel-heading"><div><h2>Laporan usaha','{section!=="backup"&&<section className="panel"><div className="panel-heading"><div><h2>Laporan usaha');
  source=replaceOnce(source,'</div></section>\n <section className="panel">','</div></section>}\n {section!=="reports"&&<section className="panel">');
  source=replaceOnce(source,'</div></div></section></div>;','</div></div></section>}</div>;');
  const infoStart=source.indexOf('<div className="drive-state">'),infoEnd=source.indexOf('<div className="backup-box">',infoStart);source=source.slice(0,infoStart)+source.slice(infoEnd);
  return{contents:source,loader:'tsx' ,resolveDir:path.dirname(args.path)};
 });
}};
await build({entryPoints:[path.join(root,'android/web/main.tsx')],bundle:true,minify:true,sourcemap:false,outfile:path.join(out,'app.js'),platform:'browser',target:'es2020',jsx:'automatic',tsconfig:path.join(root,'tsconfig.json'),plugins:[adapt],define:{'process.env.NODE_ENV':'"production"'},logLevel:'warning'});
const css=(await readFile(path.join(root,'app/globals.css'),'utf8')).replace(/^@import[^\n]+\n/,'')+'\n'+await readFile(path.join(root,'android/web/android.css'),'utf8');
await writeFile(path.join(out,'app.css'),css);await cp(path.join(root,'public/fonts'),path.join(out,'fonts'),{recursive:true});
await writeFile(path.join(out,'index.html'),'<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="light"><title>Buku Pupuk</title><link rel="stylesheet" href="/app.css"></head><body><div id="root"></div><script src="/app.js"></script></body></html>');
console.log('Bundled Android UI, Firebase client config, reports, fonts, receipts, and backup export adapter.');
