'use client';
import {useState} from 'react';
import {FileText,FileSpreadsheet,Download,ShieldCheck,Cloud,Upload,AlertCircle} from 'lucide-react';
import {reportData,type RecordRow} from '@/lib/report-data';
const rp=(v:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v);
const fileStamp=()=>{const d=new Date(),p=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}-${p(d.getHours())}-${p(d.getMinutes())}`};
export default function Reports({rows,onRestored}:{rows:RecordRow[];onRestored:()=>Promise<void>}){
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[backup,setBackup]=useState<any>(null),[filename,setFilename]=useState('');
 const data=reportData(rows,from,to);const validRange=!from||!to||from<=to;
 function download(bytes:Uint8Array|string,mime:string,filename:string){const blob=new Blob([typeof bytes==='string'?bytes:bytes.slice().buffer as ArrayBuffer],{type:mime});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 async function exportFile(type:string){setError('');setMessage('');const manual=type.startsWith('manual-'),fileType=manual?type.slice(7):type;if(fileType!=='json'&&!manual&&!validRange){setError('Tanggal awal harus sebelum atau sama dengan tanggal akhir.');return;}setBusy(type);try{
 if(type==='json'){const response=await fetch('/api/backup',{cache:'no-store'});const result=await response.json() as any;if(!response.ok)throw Error(result.error);download(JSON.stringify(result,null,2),'application/json',`buku-pupuk-cadangan-${fileStamp()}.json`);setMessage(`Cadangan lengkap ${result.recordCount} transaksi dibuat. Simpan file JSON di tempat yang aman.`);}
 else{const response=await fetch('/api/records',{cache:'no-store'});const result=await response.json() as any;if(!response.ok)throw Error(result.error);if(!Array.isArray(result))throw Error('Catatan tidak dapat dibaca.');const exporters=await import('@/lib/export-reports');const start=manual?'':from,end=manual?'':to,bytes=fileType==='pdf'?await exporters.pdfReport(result,start,end):await exporters.excelReport(result,start,end),suffix=manual?'cadangan':`${from||'awal'}-${to||'terbaru'}`,stamp=fileStamp();download(bytes,fileType==='pdf'?'application/pdf':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',`buku-pupuk-${suffix}-${stamp}.${fileType==='pdf'?'pdf':'xlsx'}`);setMessage(`${manual?'Cadangan':'Laporan'} ${fileType==='pdf'?'PDF':'Excel'} dibuat berdasarkan ${manual?'seluruh ':''}transaksi terbaru.`);}
 }catch(e){setError((e as Error).message||'File belum dapat dibuat. Coba lagi.');}finally{setBusy('');}}
 async function inspectFile(file?:File){setBackup(null);setFilename('');setError('');setMessage('');if(!file)return;try{if(file.size>5_000_000)throw Error('Cadangan maksimal 5 MB.');const result=JSON.parse(await file.text());if(result.app!=='buku-pupuk'||result.version!==1||!Array.isArray(result.records)||result.recordCount!==result.records.length)throw Error('Pilih file JSON cadangan Buku Pupuk.');setBackup(result);setFilename(file.name);}catch(e){setError((e as Error).message);}}
 async function restore(){setBusy('restore');setError('');setMessage('');try{const response=await fetch('/api/backup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(backup)});const result=await response.json() as any;if(!response.ok)throw Error(result.error);setMessage(`Pemulihan selesai: ${result.added} transaksi ditambahkan, ${result.skipped} transaksi yang sudah ada dilewati. ${result.membersAdded||0} anggota ditambahkan.`);setBackup(null);setFilename('');await onRestored();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 return <div className="report-stack">{error&&<div className="error" role="alert">{error}</div>}{message&&<div className="notice" role="status">{message}</div>}
 <section className="panel"><div className="panel-heading"><div><h2>Laporan usaha</h2><small>PDF untuk dicetak, Excel untuk diperiksa kembali.</small></div><FileText size={24}/></div><div className="report-body"><p className="report-signer"><strong>Bendahara:</strong> Muammar, S.S.T, M.Kom</p><div className="period-grid"><label>Dari tanggal<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Sampai tanggal<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={()=>{setFrom('');setTo('');}}>Semua tanggal</button></div><p className="report-help">Transaksi mengikuti periode pilihan. Kas, stok, utang, dan piutang menunjukkan posisi sampai tanggal akhir.</p><div className="report-metrics"><div><span>Total transaksi bersih</span><strong>{validRange?rp(data.transactionTotal):'—'}</strong></div><div><span>Jumlah transaksi</span><strong>{validRange?data.selected.length:'—'}</strong></div><div><span>Kas akhir periode</span><strong>{validRange?rp(data.cash):'—'}</strong></div><div><span>Sisa utang distributor</span><strong>{validRange?rp(data.debtTotal):'—'}</strong></div></div><p className="report-help">Total transaksi bersih menghitung kas masuk dikurangi kas keluar. Contoh: penarikan bank dikurangi ongkos dan biaya yang tercatat.</p><div className="report-totals"><div><span>Total penjualan</span><strong>{validRange?rp(data.sales):'—'}</strong></div><div><span>Total pembelian</span><strong>{validRange?rp(data.purchases):'—'}</strong></div><div><span>Total biaya operasional</span><strong>{validRange?rp(data.expenses):'—'}</strong></div><div><span>Total kas masuk</span><strong>{validRange?rp(data.receipts):'—'}</strong></div><div><span>Total kas keluar</span><strong>{validRange?rp(data.payments):'—'}</strong></div></div><div className="report-actions"><button className="primary" disabled={!!busy||!validRange} onClick={()=>exportFile('pdf')}><FileText size={19}/>{busy==='pdf'?'Membuat PDF…':'Unduh laporan PDF'}</button><button disabled={!!busy||!validRange} onClick={()=>exportFile('xlsx')}><FileSpreadsheet size={19}/>{busy==='xlsx'?'Membuat Excel…':'Unduh Excel (.xlsx)'}</button></div><p className="report-help">Laporan memuat ringkasan, rincian transaksi, stok, utang distributor, dan piutang petani. Penarikan bank tidak dihitung sebagai pendapatan.</p></div></section>
 <section className="panel"><div className="panel-heading"><div><h2>Cadangan dan pemulihan</h2><small>Simpan seluruh transaksi, termasuk ID dan hubungan pembayaran.</small></div><ShieldCheck size={24}/></div><div className="report-body"><div className="drive-state"><Cloud size={30}/><div><strong>Cadangan harian Google Drive</strong><p><span className="badge paid">Terjadwal</span></p><p>Cadangan harian diarahkan ke folder laporan pupuk di Google Drive setiap pukul 23.00 WIB. Cadangan pertama juga sudah dibuat.</p></div></div><div className="backup-box"><h3>Cadangan manual</h3><p>Unduh seluruh transaksi terbaru dalam tiga format. Simpan ketiganya di tempat yang aman sebagai salinan tambahan.</p><div className="backup-actions"><button disabled={!!busy} onClick={()=>exportFile('json')}><Download size={18}/>{busy==='json'?'Membuat JSON…':'Cadangan JSON'}</button><button disabled={!!busy} onClick={()=>exportFile('manual-xlsx')}><FileSpreadsheet size={18}/>{busy==='manual-xlsx'?'Membuat Excel…':'Cadangan Excel'}</button><button disabled={!!busy} onClick={()=>exportFile('manual-pdf')}><FileText size={18}/>{busy==='manual-pdf'?'Membuat PDF…':'Cadangan PDF'}</button></div></div><div className="backup-box"><h3>Pulihkan dari cadangan</h3><p>Transaksi yang belum ada akan ditambahkan. ID yang sudah tercatat dilewati. Jika isi ID berbeda, pemulihan dibatalkan.</p><label className="file-label"><Upload size={18}/> Pilih file cadangan JSON<input aria-label="Pilih file cadangan JSON" type="file" accept="application/json,.json" disabled={!!busy} onChange={e=>inspectFile(e.target.files?.[0])}/></label>{backup&&<div className="restore-preview"><AlertCircle size={20}/><div><strong>{filename}</strong><p>{backup.recordCount} transaksi · dibuat {new Date(backup.createdAt).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB</p><button className="primary" disabled={!!busy} onClick={restore}>{busy==='restore'?'Memulihkan…':'Pulihkan transaksi'}</button></div></div>}</div></div></section></div>;
}
