import {reportData,labels,type RecordRow} from './report-data';
const TREASURER='Muammar, S.S.T, M.Kom';
const money=(n:number)=>'Rp '+new Intl.NumberFormat('id-ID',{maximumFractionDigits:0}).format(n);
const fertilizerPayments=(rows:RecordRow[])=>rows.reduce((n,r)=>n+(r.type==='purchase'?r.paid:r.type==='pay'?r.amount:0),0);
const rangeLabel=(from:string,to:string)=>!from&&!to?'Semua transaksi':`${from||'Awal pencatatan'} s.d. ${to||'Tanggal terbaru'}`;
export async function excelReport(rows:RecordRow[],from='',to=''){
 const {default:ExcelJS}=await import('exceljs');const wb=new ExcelJS.Workbook();wb.creator='Buku Pupuk';wb.created=new Date();const d=reportData(rows,from,to);
 const amountFmt='"Rp "#,##0;[Red]("Rp "#,##0)',numberFmt='#,##0.00';
 function sheet(name:string,widths:number[],headers:string[],data:(string|number|Date|object)[][]){const s=wb.addWorksheet(name,{views:[{state:'frozen',ySplit:4}],pageSetup:{paperSize:9,orientation:'landscape',fitToPage:true,fitToWidth:1,fitToHeight:0}});s.columns=widths.map(width=>({width}));s.mergeCells(1,1,1,headers.length);s.getCell('A1').value='BUKU PUPUK | '+name;s.getCell('A1').font={size:18,bold:true,color:{argb:'FF174F3D'}};s.getRow(1).height=35;s.mergeCells(2,1,2,headers.length);s.getCell('A2').value=name==='Transaksi'?`Periode: ${rangeLabel(from,to)}`:`Posisi sampai: ${to||'transaksi terakhir'}`;s.getCell('A2').font={size:11,color:{argb:'FF64776D'}};s.mergeCells(3,1,3,headers.length);s.getCell('A3').value='Bendahara: '+TREASURER;s.getCell('A3').font={size:11,color:{argb:'FF64776D'}};s.getRow(4).values=headers;s.getRow(4).height=30;s.getRow(4).eachCell(c=>{c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF174F3D'}};c.font={bold:true,color:{argb:'FFFFFFFF'},size:11};c.alignment={vertical:'middle',wrapText:true};});data.forEach(values=>{const row=s.addRow(values);row.height=Math.max(30,...values.map((v,i)=>typeof v==='string'?Math.ceil(v.length/Math.max(8,widths[i]-2))*15+10:30));row.eachCell(c=>{c.font={size:11};c.alignment={vertical:'top',wrapText:true};c.border={bottom:{style:'hair',color:{argb:'FFDEE7E0'}}};if(row.number%2)c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFF3F7F1'}};});});if(data.length)s.autoFilter={from:{row:4,column:1},to:{row:4+data.length,column:headers.length}};return s;}
 const endRow=4+d.selected.length;const summary=sheet('Ringkasan',[40,28],['Keterangan','Nilai'],[
 ['Kas sebelum periode',d.opening],['Kas masuk periode',{formula:d.selected.length?`SUM(Transaksi!H5:H${endRow})`:'0',result:d.receipts}],['Kas keluar periode',{formula:d.selected.length?`SUM(Transaksi!I5:I${endRow})`:'0',result:d.payments}],['Kas sampai akhir periode',{formula:'B5+B6-B7',result:d.cash}],['Total penjualan periode',d.sales],['Total pembelian periode',d.purchases],['Biaya operasional periode',d.expenses],['Sisa utang distributor',d.debtTotal],['Sisa piutang petani',d.creditTotal],['Total transaksi bersih',d.transactionTotal]]);summary.getColumn(2).numFmt=amountFmt;summary.getCell('A2').value=`Periode: ${rangeLabel(from,to)}`;summary.getRow(8).font={bold:true};summary.getCell('A15').value='Total nilai transaksi mencakup semua aktivitas, bukan omzet.';summary.mergeCells('A15:B15');summary.getCell('A15').alignment={wrapText:true};summary.getRow(15).height=38;summary.mergeCells('A16:B16');summary.getCell('A16').value='Kas berasal dari transaksi tercatat. Penarikan bank bukan pendapatan.';summary.getCell('A16').alignment={wrapText:true};summary.getRow(16).height=38;
 summary.unMergeCells('A1:B1');summary.unMergeCells('A2:B2');summary.unMergeCells('A3:B3');
 summary.getColumn(3).width=3;summary.getColumn(4).width=28;summary.getColumn(5).width=28;
 for(const row of [1,2,3])summary.mergeCells(row,1,row,5);
 function summaryCard(start:number,title:string,value:number,description:string,color:string){
  for(let r=start;r<=start+2;r++){summary.mergeCells(r,4,r,5);const c=summary.getCell(r,4);c.fill={type:'pattern',pattern:'solid',fgColor:{argb:color}};c.alignment={vertical:'middle',wrapText:true};c.font={size:r===start+1?22:11,bold:r!==start+2,color:{argb:'FF174F3D'}};summary.getRow(r).height=r===start+2?44:32;}
  summary.getCell(start,4).value=title;summary.getCell(start+1,4).value=value;summary.getCell(start+1,4).numFmt=amountFmt;summary.getCell(start+2,4).value=description;
 }
 summaryCard(4,'Kas dari transaksi',d.transactionTotal,'Penarikan & penerimaan, dikurangi pengeluaran','FFD9EEAB');
 summaryCard(8,'Sisa utang distributor',d.debtTotal,'Pembelian yang belum dibayar','FFF3F7F1');
 summaryCard(12,'Piutang petani',d.creditTotal,'Penjualan yang belum dilunasi','FFF3F7F1');
 summaryCard(16,'Total pengeluaran pembelian pupuk',fertilizerPayments(d.selected)+d.expenses,'Pembayaran pupuk: '+money(fertilizerPayments(d.selected))+'\nBiaya operasional: '+money(d.expenses),'FFFCE4EC');
 summary.getRow(16).height=44;summary.getRow(18).height=50;summary.pageSetup.printArea='A1:E18';summary.pageSetup.fitToHeight=1;
 let running=d.opening;
 const txRows=d.selected.map((r,i)=>{const inflow=r.type==='withdraw'||r.type==='collect'?r.amount:r.type==='sale'?r.paid:0,outflow=r.type==='purchase'?r.paid:r.type==='pay'||r.type==='expense'?r.amount:0;running+=inflow-outflow;
 return [new Date(r.date+'T00:00:00Z'),labels[r.type],r.name,r.product,r.qty,r.amount,['purchase','sale'].includes(r.type)?r.paid:0,inflow,outflow,{formula:i===0?'Ringkasan!B5+H5-I5':`J${i+4}+H${i+5}-I${i+5}`,result:running},r.note,r.id,r.ref,r.sacks||r.qty/50,r.unit_price||r.unitPrice||0,r.sale_kind==='subsidi'?'Subsidi':r.sale_kind==='non_subsidi'?'Non subsidi':'',r.member_id||''];});
 const tx=sheet('Transaksi',[15,24,28,18,14,23,23,23,23,23,50,40,40,14,23,18,40],['Tanggal','Aktivitas','Nama / penerima','Pupuk','Jumlah (kg)','Nilai transaksi','Bayar saat transaksi','Kas masuk','Kas keluar','Kas berjalan','Catatan','ID transaksi','ID tagihan','Jumlah sak','Harga per sak (Rp)','Jenis penjualan','ID anggota'],txRows);if(d.selected.length){const totals=tx.addRow(['TOTAL',d.selected.length+' transaksi','','','',{formula:`SUM(H5:H${endRow})-SUM(I5:I${endRow})`,result:d.transactionTotal},'',{formula:`SUM(H5:H${endRow})`,result:d.receipts},{formula:`SUM(I5:I${endRow})`,result:d.payments}]);totals.height=32;totals.eachCell(c=>{c.font={bold:true};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFD9EEAB'}};});}tx.getColumn(1).numFmt='dd/mm/yyyy';tx.getColumn(5).numFmt=numberFmt;tx.getColumn(14).numFmt=numberFmt;tx.getColumn(15).numFmt=amountFmt;for(let c=6;c<=10;c++)tx.getColumn(c).numFmt=amountFmt;

 const s=sheet('Stok',[28,23,23,23,20,20,20],['Pupuk','Masuk (kg)','Terjual (kg)','Sisa (kg)','Masuk (sak)','Terjual (sak)','Sisa (sak)'],d.stock.map(r=>[r.product,r.incoming,r.outgoing,{formula:`B${5+d.stock.indexOf(r)}-C${5+d.stock.indexOf(r)}`,result:r.balance},r.incomingSacks,r.outgoingSacks,{formula:`E${5+d.stock.indexOf(r)}-F${5+d.stock.indexOf(r)}`,result:r.balanceSacks}]));for(let c=2;c<=7;c++)s.getColumn(c).numFmt=numberFmt;
 for(const [name,list] of [['Utang distributor',d.debts],['Piutang petani',d.credits]] as const){const sh=sheet(name,[15,30,20,23,23,23,23,40],['Tanggal','Nama','Pupuk','Total harga','Bayar awal','Pelunasan','Sisa','ID transaksi'],list.map((r,i)=>{const n=i+5;return [new Date(r.date+'T00:00:00Z'),r.name,r.product,r.amount,r.paid,r.amount-r.paid-r.remaining,{formula:`D${n}-E${n}-F${n}`,result:r.remaining},r.id];}));sh.getColumn(1).numFmt='dd/mm/yyyy';for(let c=4;c<=7;c++)sh.getColumn(c).numFmt=amountFmt;}
 return new Uint8Array(await wb.xlsx.writeBuffer());
}
export async function pdfReport(rows:RecordRow[],from='',to='',fontFiles?:[Uint8Array,Uint8Array]){
 const {PDFDocument,rgb}=await import('pdf-lib');const {default:fontkit}=await import('@pdf-lib/fontkit');const pdf=await PDFDocument.create();pdf.registerFontkit(fontkit);pdf.setTitle('Laporan Buku Pupuk');pdf.setAuthor('Buku Pupuk');const fonts=fontFiles||await Promise.all(['/fonts/DejaVuSans.ttf','/fonts/DejaVuSans-Bold.ttf'].map(async path=>{const r=await fetch(path);if(!r.ok)throw Error('Font laporan belum dapat dimuat. Coba lagi.');return new Uint8Array(await r.arrayBuffer());}));const regular=await pdf.embedFont(fonts[0],{subset:true}),bold=await pdf.embedFont(fonts[1],{subset:true});const d=reportData(rows,from,to);const green=rgb(.09,.31,.24),gray=rgb(.4,.47,.43);const W=842,H=595,M=34;let page:any,y=0;
 let firstPage=true;const safe=(s:unknown)=>String(s??'').replace(/[–—]/g,'-').replace(/[‘’]/g,"'").replace(/[“”]/g,'"').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7E\xA0-\xFF]/g,'?');
 function draw(s:unknown,x:number,top:number,size=10,isBold=false,color=rgb(.14,.23,.18)){page.drawText(safe(s),{x,y:H-top-size,size,font:isBold?bold:regular,color});}
 function newPage(){page=pdf.addPage([W,H]);y=32;draw('BUKU PUPUK',M,y,19,true,green);draw('Laporan transaksi usaha pupuk desa',M,y+27,10);draw('Bendahara: '+TREASURER,M,y+44,10);draw(rangeLabel(from,to),M,y+60,10,false,gray);if(firstPage){page.drawRectangle({x:M,y:H-204,width:W-2*M,height:62,color:rgb(.85,.93,.68)});draw('Kas dari transaksi '+money(d.transactionTotal),M+16,145,18,true,green);draw('Penarikan & penerimaan, dikurangi pengeluaran',M+16,170,9,false,gray);const gap=12,cw=(W-2*M-2*gap)/3,top=218,ch=96;
 const cards=[['Sisa utang distributor',money(d.debtTotal),'Pembelian yang belum dibayar',''],['Piutang petani',money(d.creditTotal),'Penjualan yang belum dilunasi',''],['Total pengeluaran pembelian pupuk',money(fertilizerPayments(d.selected)+d.expenses),'Pembayaran pupuk: '+money(fertilizerPayments(d.selected)),'Biaya operasional: '+money(d.expenses)]];
 cards.forEach((c,i)=>{const x=M+i*(cw+gap);page.drawRectangle({x,y:H-top-ch,width:cw,height:ch,color:i===2?rgb(.988,.894,.925):rgb(.95,.97,.94)});draw(c[0],x+10,top+10,i===2?10:11,true);draw(c[1],x+10,top+32,19,true,i===2?rgb(.4,.2,.27):green);draw(c[2],x+10,top+62,9,false,gray);if(c[3])draw(c[3],x+10,top+77,9,false,gray);});
 y=330;firstPage=false;}else y=125;}
 function wrap(value:unknown,width:number,size=9){const str=safe(value);const lines:string[]=[];let line='';for(const word of str.split(/\s+/)){let part=word;while(regular.widthOfTextAtSize(part,size)>width){let count=part.length;while(count>1&&regular.widthOfTextAtSize(part.slice(0,count),size)>width)count--;if(line){lines.push(line);line='';}lines.push(part.slice(0,count));part=part.slice(count);}const test=line?line+' '+part:part;if(regular.widthOfTextAtSize(test,size)>width&&line){lines.push(line);line=part;}else line=test;}lines.push(line||'-');return lines;}
 function section(title:string){if(y>H-100)newPage();draw(title,M,y,13,true,green);y+=28;}
 function table(headers:string[],widths:number[],data:unknown[][]){const head=()=>{const lines=headers.map((h,i)=>wrap(h,widths[i]-14));const height=Math.max(32,Math.max(...lines.map(l=>l.length))*12+16);page.drawRectangle({x:M,y:H-y-height,width:W-2*M,height,color:green});let x=M;lines.forEach((ls,i)=>{ls.forEach((h,j)=>draw(h,x+7,y+7+j*12,9,true,rgb(1,1,1)));x+=widths[i];});y+=height;};head();if(!data.length)data=[headers.map((_,i)=>i===0?'Belum ada catatan':'')];data.forEach((values,index)=>{const lines=values.map((v,i)=>wrap(v,widths[i]-14));const length=Math.max(...lines.map(l=>l.length));let offset=0;while(offset<length){let available=Math.floor((H-42-y-16)/12);if(available<1){newPage();head();available=Math.floor((H-42-y-16)/12);}const count=Math.min(available,length-offset),rh=Math.max(36,count*12+16);if(y+rh>H-42){newPage();head();continue;}if(index%2===0)page.drawRectangle({x:M,y:H-y-rh,width:W-2*M,height:rh,color:rgb(.95,.97,.94)});let x=M;lines.forEach((list,i)=>{list.slice(offset,offset+count).forEach((l,j)=>draw(l,x+7,y+7+j*12,9));x+=widths[i];});y+=rh;offset+=count;if(offset<length){newPage();head();}}});y+=24;}

 newPage();section('Ringkasan periode');table(['Keterangan','Nilai','Keterangan','Nilai'],[235,152,235,152],[['Kas sebelum periode',money(d.opening),'Kas akhir periode',money(d.cash)],['Kas masuk',money(d.receipts),'Kas keluar',money(d.payments)],['Penjualan periode',money(d.sales),'Pembelian periode',money(d.purchases)],['Biaya operasional',money(d.expenses),'Jumlah transaksi',d.selected.length]]);
 newPage();section('Rincian transaksi');table(['Tanggal','Aktivitas','Nama / pupuk','Kg','Jumlah sak','Harga per sak','Nilai (Rp)','Kas masuk (Rp)','Kas keluar (Rp)','Catatan'],[65,80,100,40,45,82,88,88,88,98],d.selected.map(r=>[r.date,labels[r.type]+(r.type==='sale'&&r.sale_kind?' / '+(r.sale_kind==='subsidi'?'Subsidi':'Non subsidi'):''),r.name+(r.product?' / '+r.product:''),r.qty||'-',r.sacks||r.qty/50||'-',(r.unit_price||r.unitPrice)?money(r.unit_price||r.unitPrice||0):'-',money(r.amount),money(r.type==='withdraw'||r.type==='collect'?r.amount:r.type==='sale'?r.paid:0),money(r.type==='purchase'?r.paid:r.type==='pay'||r.type==='expense'?r.amount:0),r.note||'-']).concat([['TOTAL',d.selected.length+' transaksi','', '-', '-', '-',money(d.transactionTotal),money(d.receipts),money(d.payments),'Kas masuk - kas keluar']]));
 section('Stok sampai akhir periode');table(['Jenis pupuk','Masuk (kg)','Terjual (kg)','Sisa (kg)','Masuk (sak)','Terjual (sak)','Sisa (sak)'],[174,100,100,100,100,100,100],d.stock.map(r=>[r.product,r.incoming,r.outgoing,r.balance,r.incomingSacks,r.outgoingSacks,r.balanceSacks]));
 for(const [title,list] of [['Sisa utang distributor',d.debts],['Sisa piutang petani',d.credits]] as const){section(title+' sampai akhir periode');table(['Tanggal','Nama / pupuk','Total harga','Sudah dibayar','Sisa'],[90,270,138,138,138],list.filter(r=>r.remaining>0).map(r=>[r.date,r.name+' / '+r.product,money(r.amount),money(r.amount-r.remaining),money(r.remaining)]));}
 pdf.getPages().forEach((p,i)=>{page=p;draw('Bendahara: '+TREASURER,M,H-38,8,false,gray);draw(`Dibuat ${new Date().toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB`,M,H-25,8,false,gray);draw(`Halaman ${i+1} / ${pdf.getPageCount()}`,W-115,H-25,8,false,gray);});return await pdf.save();
}
