import {useEffect,useState} from 'react';
import {Banknote,Wallet,Users,Save,RefreshCw,Info,TrendingUp} from 'lucide-react';
import MoneyInput from '../../app/money-input';
import type {RecordRow} from '../../lib/report-data';
import {defaultFinance,profitFromRecords,splitProfit,validFinance,type FinanceInput,type SavedFinance} from './finance-data';
import {currentStatus} from './native';
const rp=(v:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v);
export default function Finance({rows,loading,recordsError}:{rows:RecordRow[];loading:boolean;recordsError:string}){
 const [input,setInput]=useState<FinanceInput>(defaultFinance),[updatedAt,setUpdatedAt]=useState<string|null>(null),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{let alive=true;fetch('/api/finance').then(async r=>{const data=await r.json() as {plan:SavedFinance|null;error?:string};if(!r.ok)throw Error(data.error);if(!alive)return;if(data.plan){setInput(data.plan.inputs);setUpdatedAt(data.plan.updatedAt);}setReady(true);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[]);
 const valid=validFinance(input),actual=profitFromRecords(rows,input.from,input.to),base=input.basis==='manual'?input.profit:actual.profit,result=valid&&Number.isSafeInteger(base)?splitProfit(base,input):null;
 const invalidActual=input.basis==='actual'&&(loading||!!recordsError||!actual.complete||!Number.isSafeInteger(actual.profit));
 const change=<K extends keyof FinanceInput>(key:K,value:FinanceInput[K])=>{setInput(v=>({...v,[key]:value}));setMessage('');};
 async function save(e:React.FormEvent){e.preventDefault();if(!valid||invalidActual)return;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/finance',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({inputs:input,updatedAt})});const data=await r.json() as {updatedAt:string;error?:string};if(!r.ok)throw Error(data.error);setUpdatedAt(data.updatedAt);setMessage(currentStatus()?.pending?'Rencana disimpan di HP. Buka Cadangan untuk melihat status Drive.':'Rencana disimpan ke file data Drive. Periksa unggahan di aplikasi Drive.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const allocations=result?[{name:'Honor ketua / pengelola',percent:input.chairPercent,amount:result.chair,Icon:Banknote},{name:'Honor bendahara',percent:input.treasurerPercent,amount:result.treasurer,Icon:Wallet},{name:'Honor seluruh pengawas',percent:input.supervisorPercent,amount:result.supervisors,Icon:Users},{name:'Modal perputaran berikutnya',percent:result.capitalPercent,amount:result.capital,Icon:TrendingUp}]:[];
 return <div className="finance-stack">{error&&<div role="alert" className="error">{error}</div>}{message&&<div role="status" className="notice">{message}</div>}<section className="finance-intro"><span className="menu-icon"><Wallet size={25}/></span><div><h2>Honor & modal usaha</h2><p>Atur pembagian laba untuk pengurus dan putaran usaha berikutnya.</p></div></section>
 <section className="panel"><div className="panel-heading"><div><h2>Dasar pembagian laba</h2><small>Pilih laba dari transaksi atau isi laba yang sudah dihitung.</small></div><Banknote size={23}/></div><form className="finance-form" onSubmit={save}><fieldset disabled={!ready||busy}><label>Sumber laba<select value={input.basis} onChange={e=>change('basis',e.target.value as FinanceInput['basis'])}><option value="actual">Hitung dari transaksi Buku Pupuk</option><option value="manual">Isi laba sendiri / rencana</option></select></label><div className="period-grid"><label>Dari tanggal<input type="date" value={input.from} onChange={e=>change('from',e.target.value)}/></label><label>Sampai tanggal<input type="date" value={input.to} onChange={e=>change('to',e.target.value)}/></label><button type="button" onClick={()=>{setInput(v=>({...v,from:'',to:''}));setMessage('');}}>Semua tanggal</button></div>
 {input.basis==='manual'?<><label>Laba untuk dibagikan (Rp)<MoneyInput value={String(input.profit)} onChange={v=>change('profit',Number(v))}/></label><p className="report-help">Masukkan laba yang Bapak tetapkan. Contoh Rp1.000.000; angka ini tidak menambah kas atau transaksi.</p></>:<><dl className="finance-facts"><div><dt>Nilai penjualan</dt><dd>{rp(actual.sales)}</dd></div><div><dt>Harga pokok pupuk terjual</dt><dd>{rp(actual.cogs)}</dd></div><div><dt>Biaya operasional periode</dt><dd>{rp(actual.expenses)}</dd></div><div className="finance-profit"><dt>Laba sebelum pembagian</dt><dd>{invalidActual?'Belum dapat dihitung':rp(actual.profit)}</dd></div></dl><details className="finance-method"><summary>Cara menghitung laba</summary><p>Penjualan dikurangi harga beli pupuk yang terjual dan seluruh biaya operasional pada periode pilihan. Harga pokok memakai FIFO: stok yang masuk lebih dahulu dianggap terjual lebih dahulu. Pembelian pada tanggal yang sama dihitung sebelum penjualan. Penarikan bank dan pelunasan tidak menambah laba.</p><p>Penjualan termasuk piutang. Nilai ini belum memperhitungkan pajak yang belum dicatat. Pastikan biaya sudah lengkap sebelum menetapkan honor.</p></details>{!actual.complete&&<p className="error">Ada penjualan sebelum stok pembeliannya tercatat. Periksa tanggal transaksi sebelum memakai laba otomatis.</p>}{recordsError&&<p className="error">Data transaksi belum dapat dibaca: {recordsError}</p>}</>}
 <div className="finance-divider"/><h3>Persentase honor</h3><p className="report-help">Sisa persentase otomatis menjadi modal. Honor pengawas adalah total untuk seluruh pengawas.</p><div className="finance-percent-grid">{[['chairPercent','Ketua / pengelola (%)'],['treasurerPercent','Bendahara (%)'],['supervisorPercent','Seluruh pengawas (%)']].map(([key,label])=><label key={key}>{label}<input type="number" min="0" max="100" step="0.01" required value={Number.isFinite(input[key as 'chairPercent'|'treasurerPercent'|'supervisorPercent'])?input[key as 'chairPercent'|'treasurerPercent'|'supervisorPercent']:''} onChange={e=>change(key as 'chairPercent'|'treasurerPercent'|'supervisorPercent',e.target.value===''?NaN:Number(e.target.value))}/></label>)}</div><label>Jumlah pengawas<input type="number" min="1" max="100" step="1" required value={Number.isFinite(input.supervisorCount)?input.supervisorCount:''} onChange={e=>change('supervisorCount',e.target.value===''?NaN:Number(e.target.value))}/></label><label>Catatan pembagian<textarea maxLength={1000} value={input.note} onChange={e=>change('note',e.target.value)} placeholder="Contoh: hasil kesepakatan pengurus untuk periode ini"/></label>{!valid&&<p className="error" role="alert">Total honor maksimal 100%. Periksa angka, tanggal, dan jumlah pengawas.</p>}<button className="primary" disabled={!valid||invalidActual} type="submit">{busy?<RefreshCw size={19}/>:<Save size={19}/>} {busy?'Menyimpan…':'Simpan rencana keuangan'}</button></fieldset></form></section>
 {result&&!invalidActual&&<><div className="finance-summary"><div className="card expenditure"><span>Total honor · {result.honorPercent}%</span><strong>{rp(result.honor)}</strong><small>Ketua, bendahara, dan seluruh pengawas</small></div><div className="card cash"><span>Tambahan modal · {result.capitalPercent}%</span><strong>{rp(result.capital)}</strong><small>Bagian laba untuk putaran berikutnya</small></div></div><section className="panel"><div className="panel-heading"><h2>Rincian pembagian</h2><Users size={22}/></div><div className="finance-allocation">{allocations.map(({name,percent,amount,Icon})=><div key={name}><span className="menu-icon"><Icon size={21}/></span><div><strong>{name}</strong><small>{percent}% dari laba {rp(result.profit)}</small></div><b>{rp(amount)}</b></div>)}</div><div className="finance-allocation-total"><span>Total dibagikan</span><strong>{rp(result.profit)}</strong></div>{input.supervisorCount>1&&<p className="finance-footnote">Honor pengawas dibagi ke {input.supervisorCount} orang: {rp(result.perSupervisor)} per orang{result.supervisorRemainder>0?`; sisa pembulatan ${rp(result.supervisorRemainder)} diberikan kepada satu pengawas`:''}. Total tetap {rp(result.supervisors)}.</p>}</section>{base<=0&&<p className="finance-callout"><Info size={20}/>Belum ada laba positif untuk dibagikan. Honor dan tambahan modal dihitung Rp0.</p>}</>}
 <section className="panel"><div className="panel-heading"><h2>Posisi kas & modal saat ini</h2><Wallet size={22}/></div><dl className="finance-facts finance-position"><div><dt>Kas dari transaksi</dt><dd>{rp(actual.cash)}</dd></div><div><dt>Modal tertanam pada stok</dt><dd>{actual.complete?rp(actual.stockCost):'Periksa tanggal stok'}</dd></div><div><dt>Sisa utang distributor</dt><dd>{rp(actual.debt)}</dd></div><div><dt>Piutang petani</dt><dd>{rp(actual.credit)}</dd></div></dl><p className="finance-footnote">Posisi sampai tanggal akhir. Bagian modal di atas adalah tambahan dari laba; modal pokok usaha tetap perlu diputar kembali. Laba bisa belum diterima tunai apabila penjualan masih berupa piutang.</p></section><p className="finance-callout"><Info size={20}/>Ini rencana pembagian. Menyimpan rencana tidak mengurangi kas. Jika honor sudah dibayar, catat sekali sebagai Biaya operasional agar kas dan laporan sesuai.</p></div>;
}
