import {useEffect,useState} from 'react';
import {LockKeyhole,ShieldCheck,LogIn,KeyRound,LoaderCircle,Eye,EyeOff} from 'lucide-react';
import AppCopyright from './copyright';
import {native} from './native';
export default function Login({configured,lockRemainingSeconds,onUnlock}:{configured:boolean;lockRemainingSeconds:number;onUnlock:()=>Promise<void>}){
 const [pin,setPin]=useState(''),[repeat,setRepeat]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[visible,setVisible]=useState(false),[remaining,setRemaining]=useState(lockRemainingSeconds);
 useEffect(()=>{if(remaining<=0)return;const timer=setTimeout(()=>setRemaining(n=>Math.max(0,n-1)),1000);return()=>clearTimeout(timer);},[remaining]);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(!configured&&pin!==repeat){setError('PIN dan konfirmasi PIN belum sama.');return;}setBusy(true);try{await native(configured?'loginAuth':'setupAuth',{pin});setPin('');setRepeat('');await onUnlock();}catch(e){setError((e as Error).message);const status=await native<{lockRemainingSeconds:number}>('authStatus').catch(()=>null);if(status)setRemaining(status.lockRemainingSeconds);}finally{setBusy(false);}}
 return <main className="login-screen"><section className="login-card"><div className="login-logo"><LockKeyhole size={30}/></div><p className="login-kicker">BUKU PUPUK · BUMDes DESA KABAT</p><h1>{configured?'Masuk ke Buku Pupuk':'Buat PIN aplikasi'}</h1><p className="login-lead">{configured?'Masukkan PIN untuk membuka catatan usaha.':'Buat PIN pribadi untuk mengunci aplikasi pada HP ini.'}</p><form className="login-form" onSubmit={submit}><label>{configured?'PIN aplikasi':'PIN baru (6–12 angka)'}<span className="login-pin-wrap"><input autoComplete="off" autoFocus inputMode="numeric" maxLength={12} pattern="[0-9]{6,12}" required type={visible?'text':'password'} value={pin} onChange={e=>{setPin(e.target.value.replace(/\D/g,'').slice(0,12));setError('');}} placeholder="••••••"/><button type="button" aria-label={visible?'Sembunyikan PIN':'Lihat PIN'} onClick={()=>setVisible(v=>!v)}>{visible?<EyeOff size={19}/>:<Eye size={19}/>}</button></span></label>{!configured&&<label>Ulangi PIN<input autoComplete="off" inputMode="numeric" maxLength={12} pattern="[0-9]{6,12}" required type={visible?'text':'password'} value={repeat} onChange={e=>setRepeat(e.target.value.replace(/\D/g,'').slice(0,12))} placeholder="Ketik ulang PIN"/></label>}{error&&<p className="login-error" role="alert">{error}</p>}{remaining>0&&<p className="login-lockout" role="status">Coba lagi dalam {Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')} menit</p>}<button className="primary login-submit" type="submit" disabled={busy||remaining>0}>{busy?<LoaderCircle className="spinning" size={19}/>:configured?<LogIn size={19}/>:<KeyRound size={19}/>} {busy?'Memeriksa…':configured?'Masuk':'Simpan PIN'}</button></form><div className="login-note"><ShieldCheck size={18}/><p>PIN disimpan di HP dalam bentuk terlindungi. PIN tidak dimasukkan ke data transaksi atau cadangan Google Drive.</p></div><AppCopyright/></section></main>;
}
