import {useState} from 'react';
import {LockKeyhole,ShieldCheck,LogIn,UserPlus,LoaderCircle,Eye,EyeOff,Mail,KeyRound} from 'lucide-react';
import AppCopyright from './copyright';
import {native} from './native';
const OWNER_EMAIL='xmuammar@gmail.com';
export default function Login({configured,onUnlock}:{configured:boolean;onUnlock:()=>Promise<void>}){
 const [mode,setMode]=useState<'signin'|'signup'>(configured?'signin':'signup'),[password,setPassword]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[visible,setVisible]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');setMessage('');setBusy(true);try{
  if(mode==='signup'){await native('setupAuth',{email:OWNER_EMAIL,password});setPassword('');await onUnlock();return;}
  await native('loginAuth',{email:OWNER_EMAIL,password});setPassword('');await onUnlock();
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function reset(){setError('');setMessage('');setBusy(true);try{await native('resetPassword',{email:OWNER_EMAIL});setMessage('Tautan pengaturan ulang kata sandi dikirim ke '+OWNER_EMAIL+'.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="login-screen"><section className="login-card"><div className="login-logo"><LockKeyhole size={30}/></div><p className="login-kicker">BUKU PUPUK · BUMDes DESA KABAT</p><h1>{mode==='signin'?'Masuk ke Buku Pupuk':'Buat akun BUMDes'}</h1><p className="login-lead">Data usaha tersimpan di Firebase dan dapat dibuka di HP lain dengan akun yang sama.</p><form className="login-form" onSubmit={submit}><label>Akun Firebase<span className="login-email"><Mail size={18}/><input readOnly value={OWNER_EMAIL} aria-label="Email akun BUMDes"/></span></label><label>Kata sandi Firebase<span className="login-pin-wrap"><input autoComplete={mode==='signin'?'current-password':'new-password'} autoFocus minLength={6} required type={visible?'text':'password'} value={password} onChange={e=>{setPassword(e.target.value);setError('');}} placeholder="Minimal 6 karakter"/><button type="button" aria-label={visible?'Sembunyikan kata sandi':'Lihat kata sandi'} onClick={()=>setVisible(v=>!v)}>{visible?<EyeOff size={19}/>:<Eye size={19}/>}</button></span></label>{error&&<p className="login-error" role="alert">{error}</p>}{message&&<p className="login-success" role="status">{message}</p>}<button className="primary login-submit" type="submit" disabled={busy}>{busy?<LoaderCircle className="spinning" size={19}/>:mode==='signin'?<LogIn size={19}/>:<UserPlus size={19}/>} {busy?'Memproses…':mode==='signin'?'Masuk':'Daftar & langsung masuk'}</button></form>{mode==='signin'&&<button className="login-reset" disabled={busy} onClick={reset}><KeyRound size={16}/> Lupa kata sandi?</button>}<button className="login-switch" disabled={busy} onClick={()=>{setMode(m=>m==='signin'?'signup':'signin');setError('');setMessage('');}}>{mode==='signin'?'Akun belum dibuat? Buat akun':'Sudah punya akun? Masuk'}</button><div className="login-note"><ShieldCheck size={18}/><p>Hanya akun BUMDes {OWNER_EMAIL} yang dapat membuka database. Setelah daftar, aplikasi langsung masuk tanpa verifikasi email. Kata sandi dimasukkan langsung di HP dan tidak disimpan aplikasi.</p></div><AppCopyright/></section></main>;
}
