import AppCopyright from './copyright';
import {useEffect,useRef,useState} from 'react';
import {Home,ShoppingBag,ShoppingBasket,Users,Grid2X2,Package,Calculator,Wallet,FileText,Cloud,Banknote,BookOpen,X,ChevronRight,LockKeyhole} from 'lucide-react';
declare global {interface Window{BukuMenu?:string}}
const primary=[{name:'Ringkasan',Icon:Home},{name:'Pembelian',Icon:ShoppingBag},{name:'Penjualan',Icon:ShoppingBasket},{name:'Anggota',Icon:Users}];
const extra=[{name:'Keuangan',description:'Honor pengurus & modal berikutnya',Icon:Banknote},{name:'Stok pupuk',description:'Persediaan Urea & Phoska',Icon:Package},{name:'Simulasi',description:'Rencana penjualan dari data aktual',Icon:Calculator},{name:'Buku kas',description:'Seluruh uang masuk dan keluar',Icon:Wallet},{name:'Laporan',description:'Ringkasan PDF dan Excel',Icon:FileText},{name:'Cadangan',description:'Firebase & arsip Drive',Icon:Cloud}];
export function MobileHeader({tab}:{tab:string}){return <div className="mobile-appbar"><div className="mobile-brand"><span className="mobile-brand-icon"><BookOpen size={22}/></span><div><strong>Buku Pupuk</strong><small>BUMDes Desa Kabat</small></div></div><span className="mobile-section">{tab}</span></div>;}
export function BottomNavigation({tab,onSelect}:{tab:string;onSelect:(tab:string)=>void}){
 const [open,setOpen]=useState(false);const more=useRef<HTMLButtonElement>(null),sheet=useRef<HTMLElement>(null);
 useEffect(()=>{if(!open)return;const previous=document.body.style.overflow,trigger=more.current;document.body.style.overflow='hidden';sheet.current?.querySelector<HTMLButtonElement>('button')?.focus();
  const close=()=>setOpen(false);const key=(e:KeyboardEvent)=>{if(e.key==='Escape')close();if(e.key==='Tab'){const buttons=sheet.current?.querySelectorAll<HTMLButtonElement>('button');if(!buttons?.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};
  window.addEventListener('keydown',key);window.addEventListener('buku-close-menu',close);return()=>{document.body.style.overflow=previous;window.removeEventListener('keydown',key);window.removeEventListener('buku-close-menu',close);trigger?.focus();};
 },[open]);
 function select(name:string){setOpen(false);onSelect(name);window.scrollTo?.({top:0,behavior:'instant'});}
 return <><nav className="mobile-bottom-nav" aria-label="Navigasi utama">{primary.map(({name,Icon})=><button type="button" key={name} aria-current={tab===name?'page':undefined} className={tab===name?'active':''} onClick={()=>select(name)}><Icon size={22} aria-hidden="true"/><span>{name}</span></button>)}<button type="button" ref={more} aria-label="Lainnya" aria-expanded={open} aria-controls="mobile-more-menu" className={extra.some(item=>item.name===tab)?'active':''} onClick={()=>setOpen(true)}><Grid2X2 size={22} aria-hidden="true"/><span>Lainnya</span></button></nav>
 {open&&<div className="mobile-menu-overlay" onClick={()=>setOpen(false)}><section id="mobile-more-menu" className="mobile-menu-sheet" role="dialog" aria-modal="true" aria-labelledby="more-title" ref={sheet} onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><div className="mobile-menu-heading"><div><h2 id="more-title">Menu lainnya</h2><p>Kelola usaha pupuk Anda</p></div><button aria-label="Tutup menu" onClick={()=>setOpen(false)}><X size={22}/></button></div><div className="mobile-menu-list">{extra.map(({name,description,Icon})=><button key={name} onClick={()=>select(name)} aria-label={name} aria-current={tab===name?'page':undefined}><span className="menu-icon"><Icon size={23}/></span><span><strong>{name}</strong><small>{description}</small></span><ChevronRight size={18}/></button>)}</div><button type="button" className="mobile-lock-button" onClick={async()=>{setOpen(false);await window.BukuAuthLock?.();}}><LockKeyhole size={19}/> Kunci aplikasi</button><AppCopyright/></section></div>}</>;
}
