/* eslint @typescript-eslint/no-require-imports: "off" -- CJS harness loads optional dependencies from the selected test runtime. */
// DOM integration harness. It checks rendered controls and exports, not Android provider or screen layout.
const {JSDOM,VirtualConsole}=require(process.env.BUKU_JSDOM_MODULE||'jsdom');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
(async()=>{
 const root=process.cwd(),errors=[];
 const make=(id,type,values)=>({id,type,date:'2026-10-03',name:'Pengujian',product:'',qty:0,sacks:0,unit_price:0,amount:1,paid:0,ref:'',note:'',receipt_name:'',receipt_data:'',sale_kind:'',member_id:'',...values});
 const rows=[make('w','withdraw',{amount:500000}),make('p','purchase',{product:'Urea',qty:500,sacks:10,unit_price:20000,amount:200000,paid:200000}),make('e','expense',{amount:20000})];
 let state={snapshot:{app:'buku-pupuk',version:1,createdAt:new Date().toISOString(),recordCount:rows.length,records:rows,members:[],simulation:null},revision:1,pending:false,connected:true,fileName:'test.json',lastSavedAt:new Date().toISOString(),error:''};let exported=[];
 const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));vc.on('error',e=>errors.push(String(e)));
 const dom=new JSDOM('<div id="root"></div>',{url:'https://appassets.androidplatform.net/',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc}),w=dom.window;
 Object.assign(w,{TextEncoder,TextDecoder,Request,Response,Headers});w.crypto.randomUUID=()=>crypto.randomUUID();w.confirm=()=>true;w.scrollTo=()=>{};
 w.fetch=async url=>new Response(await fs.readFile(path.join(root,'android/native/assets',new URL(String(url),w.location.href).pathname)),{status:200});
 w.BukuNative={call:raw=>{const req=JSON.parse(raw);let result,error;try{switch(req.operation){case 'load':result=state;break;case 'commit':assert.equal(req.payload.revision,state.revision);state={...state,snapshot:req.payload.snapshot,revision:state.revision+1,pending:true,error:'Offline uji'};result=state;break;case 'sync':state={...state,pending:false,error:''};result=state;break;case 'driveFolder':result={opened:true};break;case 'openDatabase':case 'createDatabase':case 'previewDrive':result={token:'test',snapshot:state.snapshot};break;case 'acceptDatabase':result=state;break;case 'saveExport':exported.push(req.payload);result={providerWritten:true,filename:req.payload.filename};break;default:throw Error('Unsupported operation '+req.operation);}}catch(e){error=e.message;}setTimeout(()=>w.BukuReply(JSON.stringify({id:req.id,result,error,ok:!error})),0);}};
 w.eval(await fs.readFile('android/native/assets/app.js','utf8'));
 const wait=async fn=>{const start=Date.now();while(!fn()){if(Date.now()-start>20000)throw Error('Timeout: '+w.document.body.textContent.slice(-1200));await new Promise(r=>setTimeout(r,20));}};
 const button=name=>[...w.document.querySelectorAll('button')].find(b=>b.textContent.trim()===name);
 const menu=async name=>{if(!button(name)){button('Lainnya').click();await wait(()=>w.document.querySelector('.mobile-menu-overlay'));}const target=[...w.document.querySelectorAll('button')].find(b=>b.getAttribute('aria-label')===name)||button(name);assert.ok(target,'menu '+name);target.click();await wait(()=>w.document.querySelector('h1')?.textContent===(name==='Ringkasan'?'Catatan pupuk desa':name));};
 const label=name=>[...w.document.querySelectorAll('label')].find(b=>b.childNodes[0].textContent===name)?.querySelector('input,select,textarea');
 const change=(element,value)=>{assert.ok(element,'input exists');Object.getOwnPropertyDescriptor(element.tagName==='SELECT'?w.HTMLSelectElement.prototype:element.tagName==='TEXTAREA'?w.HTMLTextAreaElement.prototype:w.HTMLInputElement.prototype,'value').set.call(element,value);element.dispatchEvent(new w.Event(element.tagName==='SELECT'?'change':'input',{bubbles:true}));};
 try{
  await wait(()=>w.document.body.textContent.includes('Rp 280.000'));assert.equal(w.document.querySelectorAll('.mobile-bottom-nav button').length,5);assert.equal(w.document.querySelector('.mobile-bottom-nav button[aria-current=page]').textContent,'Ringkasan');assert.ok([...w.document.querySelectorAll('.mobile-bottom-nav button')].every(b=>b.querySelector('svg')));assert.ok(!w.document.querySelector('aside'));assert.ok(!w.document.querySelector('.android-drive'));button('Anggota').click();await wait(()=>button('Tambah anggota'));button('Tambah anggota').click();await wait(()=>label('Nama anggota'));change(label('Nama anggota'),'Anggota pengujian');button('Simpan anggota').click();await wait(()=>state.snapshot.members.length===1&&!w.document.querySelector('.overlay'));
  button('Catat penjualan').click();await wait(()=>label('Pilih anggota'));change(label('Pilih anggota'),state.snapshot.members[0].id);change(label('Total sak'),'1');await wait(()=>label('Jumlah (kg)').value==='50');change(label('Harga per sak (Rp)'),'120000');await wait(()=>label('Total harga pupuk (Rp)').value==='120.000');assert.equal(label('Harga per sak (Rp)').value,'120.000');change(label('Uang diterima saat menjual (Rp)'),'120000');button('Simpan catatan').click();await wait(()=>state.snapshot.recordCount===4&&!w.document.querySelector('.overlay'));assert.equal(state.snapshot.records[3].name,'Anggota pengujian');assert.equal(state.pending,true);assert.match(w.document.body.textContent,/Tersimpan di HP/);assert.ok(!button('Kirim ke Drive'),'Drive controls absent outside Cadangan');await menu('Cadangan');assert.match(w.document.body.textContent,/Drive belum diperbarui/);button('Kirim ke Drive').click();await wait(()=>!state.pending);button('Muat dari Drive').click();await wait(()=>w.document.querySelector('h1').textContent==='Cadangan'&&!button('File Drive').disabled);button('File Drive').click();await wait(()=>!button('File Drive').disabled);assert.equal(w.document.querySelector('h1').textContent,'Cadangan');button('Buka folder Drive').click();await wait(()=>!button('File Drive').disabled);
  await menu('Keuangan');await wait(()=>label('Sumber laba')&&!label('Sumber laba').disabled);assert.match(w.document.body.textContent,/80.000/);change(label('Sumber laba'),'manual');await wait(()=>label('Laba untuk dibagikan (Rp)'));change(label('Laba untuk dibagikan (Rp)'),'1000000');await wait(()=>w.document.body.textContent.includes('Rp 700.000'));assert.equal(label('Laba untuk dibagikan (Rp)').value,'1.000.000');assert.match(w.document.body.textContent,/150.000/);assert.match(w.document.body.textContent,/100.000/);assert.match(w.document.body.textContent,/50.000/);button('Simpan rencana keuangan').click();await wait(()=>state.snapshot.finance?.inputs.profit===1000000);assert.equal(state.snapshot.recordCount,4);await menu('Ringkasan');await menu('Keuangan');await wait(()=>label('Laba untuk dibagikan (Rp)')?.value==='1.000.000');
  await menu('Simulasi');await wait(()=>w.document.querySelector('h1').textContent==='Simulasi');assert.ok(!w.document.body.textContent.includes('Anggaran dan target'));await menu('Laporan');assert.ok(!button('Cadangan JSON'));assert.ok(!button('File Drive'));await wait(()=>button('Simpan PDF ke Drive'));button('Simpan PDF ke Drive').click();await wait(()=>exported.length===1);await wait(()=>!button('Simpan Excel ke Drive').disabled);button('Simpan Excel ke Drive').click();await wait(()=>exported.length===2);await menu('Cadangan');assert.ok(!button('Simpan PDF ke Drive'));await wait(()=>!button('Cadangan JSON').disabled);button('Cadangan JSON').click();await wait(()=>exported.length===3);
  const json=JSON.parse(Buffer.from(exported[2].base64,'base64'));assert.equal(json.recordCount,4);assert.equal(json.members.length,1);assert.equal(json.finance.inputs.profit,1000000);assert.equal(Buffer.from(exported[0].base64,'base64').subarray(0,4).toString(),'%PDF');assert.equal(Buffer.from(exported[1].base64,'base64').subarray(0,2).toString(),'PK');assert.deepEqual(errors,[]);
  console.log('PASS: DOM members, subsidized member selection, money grouping, sacks/kg, offline notice, sync action, fixed icon navigation, separated reports/backup, Drive-only-in-Cadangan controls, saved honor/capital plan in JSON, real simulation, bundled PDF/Excel/JSON exports.');
 }finally{w.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
