import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const {chromium}=createRequire(import.meta.url)('playwright');
import assert from 'node:assert/strict';
const root=process.cwd(),out=path.join(root,'.sites-runtime/android/qa');await mkdir(out,{recursive:true});
const fixture=JSON.parse(await readFile(process.env.BUKU_TEST_SNAPSHOT||'android/tests/fixture.json','utf8'));
const csp="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self'; connect-src 'self'; object-src 'none'; frame-src 'none'; base-uri 'none'";
const server=createServer(async(req,res)=>{try{const p=new URL(req.url,'http://localhost').pathname;const f=path.join(root,'android/native/assets',p==='/'?'index.html':p);const bytes=await readFile(f);res.writeHead(200,{'Content-Type':p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':p.endsWith('.ttf')?'font/ttf':'text/html','Content-Security-Policy':csp});res.end(bytes);}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:process.env.BUKU_TEST_CHROME,args:['--no-sandbox','--single-process','--no-zygote','--disable-gpu']});
const context=await browser.newContext({viewport:{width:393,height:852},deviceScaleFactor:1});
await context.addInitScript(seed=>{let state={snapshot:seed,revision:1,pending:false,connected:true,fileName:'buku-pupuk-database-android-2026-10-03.json',lastSavedAt:new Date().toISOString(),error:''};window.__exports=[];window.BukuNative={call:raw=>{const req=JSON.parse(raw);let result,error;try{switch(req.operation){case 'load':result=state;break;case 'commit':if(req.payload.revision!==state.revision)throw Error('stale');state={...state,snapshot:req.payload.snapshot,revision:state.revision+1,pending:true,error:'Internet belum tersedia.'};result=state;break;case 'sync':state={...state,pending:false,error:''};result=state;break;case 'previewDrive':result={token:'test',snapshot:state.snapshot};break;case 'acceptDatabase':result=state;break;case 'saveExport':window.__exports.push(req.payload);result={filename:req.payload.filename,providerWritten:true};break;default:throw Error('Unsupported mock operation '+req.operation);}}catch(e){error=e.message;}setTimeout(()=>window.BukuReply(JSON.stringify({id:req.id,ok:!error,result,error})),5);}};},fixture);
const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
try{
 await page.goto('http://127.0.0.1:'+server.address().port);await page.getByRole('heading',{name:'Catatan pupuk desa'}).waitFor();await page.getByText(/Rp\s*280\.000/).first().waitFor();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'mobile page width');await page.screenshot({path:path.join(out,'android-summary.png'),fullPage:true});
 await page.getByRole('button',{name:'Catat penjualan',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Jenis penjualan').selectOption('non_subsidi');await dialog.getByLabel('Nama petani / kelompok tani').fill('Pembeli pengujian');await dialog.getByLabel('Total sak',{exact:true}).fill('1');await dialog.getByLabel('Harga per sak (Rp)').fill('120000');assert.equal(await dialog.getByLabel('Harga per sak (Rp)').inputValue(),'120.000');assert.equal(await dialog.getByLabel('Jumlah (kg)').inputValue(),'50');assert.equal(await dialog.getByLabel('Total harga pupuk (Rp)').inputValue(),'120.000');await dialog.getByLabel('Uang diterima saat menjual (Rp)').fill('120000');
 await dialog.getByLabel('Kwitansi / bukti transaksi').setInputFiles({name:'kwitansi.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a0i0AAAAASUVORK5CYII=','base64')});await dialog.getByAltText('Kwitansi terlampir').waitFor();await page.screenshot({path:path.join(out,'android-sale.png'),fullPage:true});await dialog.getByRole('button',{name:'Simpan catatan',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByText(/Tersimpan di HP · Drive belum diperbarui/).waitFor();await page.getByRole('button',{name:'Kirim ke Drive',exact:true}).click();await page.getByText('Data dibaca / ditulis ke file Drive',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Simulasi',exact:true}).click();await page.getByRole('heading',{name:'Simulasi',exact:true}).waitFor();await page.screenshot({path:path.join(out,'android-simulation.png'),fullPage:true});
 await page.getByRole('button',{name:'Laporan & cadangan',exact:true}).click();await page.getByRole('button',{name:'Simpan PDF ke Drive',exact:true}).click();await page.getByText('File PDF ditulis ke file Drive. Periksa status unggahan di aplikasi Drive.',{exact:true}).waitFor({timeout:60000});await page.getByRole('button',{name:'Simpan Excel ke Drive',exact:true}).click();await page.getByText('File Excel ditulis ke file Drive. Periksa status unggahan di aplikasi Drive.',{exact:true}).waitFor({timeout:60000});await page.getByRole('button',{name:'Cadangan JSON',exact:true}).click();await page.getByText(new RegExp(`Cadangan lengkap ${fixture.recordCount+1} transaksi ditulis`)).waitFor();
 const exported=await page.evaluate(()=>window.__exports);assert.equal(exported.length,3);for(const f of exported){const ext=f.filename.split('.').pop();await writeFile(path.join(out,'android-report.'+ext),Buffer.from(f.base64,'base64'));}const backup=JSON.parse(Buffer.from(exported.find(f=>f.mime==='application/json').base64,'base64').toString());assert.equal(backup.records.length,fixture.recordCount+1);assert.equal(backup.records.find(r=>r.name==='Pembeli pengujian').receipt_name,'kwitansi.jpg');
 await page.screenshot({path:path.join(out,'android-reports.png'),fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: mobile layout, sale kg/sacks, money separators, receipt attachment, offline status, sync, simulation, PDF/Excel/JSON exports.');
}finally{await context.close();await browser.close();await new Promise(r=>server.close(r));}
