'use client';
import {useState} from 'react';
import {Plus,Pencil,X} from 'lucide-react';
import type {Member} from '@/lib/member-data';
export default function Members({members,onChanged}:{members:Member[];onChanged:()=>Promise<void>}){
 const [form,setForm]=useState<Member|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [search,setSearch]=useState('');
 async function save(e:React.FormEvent){e.preventDefault();if(!form)return;setBusy(true);setError('');try{const r=await fetch('/api/members',{method:form.id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}),d=await r.json() as any;if(!r.ok)throw Error(d.error);await onChanged();setForm(null);setNotice('Data anggota berhasil disimpan.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const shown=members.filter(m=>(m.name+' '+m.farmer_group).toLowerCase().includes(search.toLowerCase()));
 return <><section className="panel"><div className="panel-heading"><div><h2>Daftar anggota</h2><small>{members.length} anggota</small></div><button className="primary" onClick={()=>{setError('');setForm({id:'',name:'',nik:'',farmer_group:'',address:'',updated_at:''});}}><Plus size={18}/>Tambah anggota</button></div><div className="report-body">{notice&&<div className="notice">{notice}</div>}<label>Cari nama / kelompok tani<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari anggota"/></label></div>{shown.length?<div className="table-wrap"><table><thead><tr><th>Nama</th><th>NIK</th><th>Kelompok tani</th><th>Alamat</th><th>Aksi</th></tr></thead><tbody>{shown.map(m=><tr key={m.id}><td><strong>{m.name}</strong></td><td>{m.nik||'—'}</td><td>{m.farmer_group||'—'}</td><td>{m.address||'—'}</td><td><button onClick={()=>{setError('');setForm({...m});}}><Pencil size={15}/>Edit</button></td></tr>)}</tbody></table></div>:<div className="empty">Belum ada anggota yang sesuai. Tambahkan anggota untuk memilih nama pada penjualan subsidi.</div>}</section>{form&&<div className="overlay"><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="member-title"><div className="panel-heading"><h2 id="member-title">{form.id?'Edit anggota':'Tambah anggota'}</h2><button aria-label="Tutup anggota" onClick={()=>setForm(null)}><X/></button></div><form onSubmit={save}><label>Nama anggota<input required maxLength={200} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>NIK (opsional)<input inputMode="numeric" pattern="[0-9]{16}" maxLength={16} value={form.nik} onChange={e=>setForm({...form,nik:e.target.value.replace(/\D/g,'')})}/></label><label>Kelompok tani<input maxLength={200} value={form.farmer_group} onChange={e=>setForm({...form,farmer_group:e.target.value})}/></label><label>Alamat<textarea maxLength={1000} value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label>{error&&<div className="error" role="alert">{error}</div>}<div className="form-actions"><button type="button" onClick={()=>setForm(null)}>Batal</button><button className="primary" disabled={busy}>{busy?'Menyimpan…':'Simpan anggota'}</button></div></form></section></div>}</>;
}
